### ISSUE TITLE
Add configurations and/or command line options to differentiate between system-wide and user-specific installations

### ISSUE THREAD

**Issue by audreytoskin** [chocolatey/choco#1334]
I'm noticing a lot of packages which install under the invoking user's `AppData` directory, even when calling from an admin instance of PowerShell. Installing to the user's `AppData` directory is useful for *unprivileged users* who want to use their favorite software, I guess, but it's a little annoying for *administrators* of multi-user machines (I share a desktop at home), because then each user needs to maintain their own copy of each application. And I think it's largely irrelevant for single-user machines, because the owner and only user of the computer should easily be able to run as admin without any trouble.

As far as I know, the only way to force Chocolatey to do a system-wide installation to the standard directories is with the `--install-directory` command line option. But that's apparently only available to Pro subscribers, and I would have expected such a feature to be for choosing custom installation locations rather than enforcing the `C:\Program Files` standard.

**Comment by ferventcoder** [comment]
I believe this is package/software dependent. Most of this would be within the community package repository, correct? Not packages you are creating or using in your organization (if being used internally with an organization that creates and has an internal package repository)?

In Chocolatey, "package" is the nupkg file or Chocolatey package, "software" is the binaries that are put somewhere on the system, whether it be in the package directory, natively installed through an installer, or otherwise.

I'm assuming based on that context, you are referring to the software installers putting things in strange locations, and not always Program Files as you might expect. Is that correct? That's pretty standard with Windows Installers, that they sometimes install just about anywhere by default. There are some installers that don't do well in Program Files (e.g. Ruby, Python), so they don't install there. There are others. 

The long and short of this is that it is not Chocolatey doing this, it is either the packaging or (***most likely***) the software installers themselves.

If it something else, might be worth discussing more at length. Do you have some specific examples here?

**Comment by ferventcoder** [comment]
> As far as I know, the only way to force Chocolatey to do a system-wide installation to the standard directories is with the --install-directory command line option. But that's apparently only available to Pro subscribers, and I would have expected such a feature to be for choosing custom installation locations rather than enforcing the `C:\Program Files` standard.

That feature is for choosing custom install locations. `C:\Program Files` may be a standard, but there are installers out there that don't use it.

You can also set custom install locations without needing the ubiquitous install directory switch, as mentioned in the documentation.

**Comment by terrycloth** [comment]
> I'm assuming based on that context, you are referring to the software installers putting things in strange locations, and not always Program Files as you might expect. Is that correct?

Yes, that's what I'm talking about. I'd assumed the issue was that packagers were doing user-specific installations because there wasn't a clear way to differentiate between user and system wide installations. I don't *think* I'd noticed many applications installing outside of `C:\Program Files` before trying Chocolatey, but I suppose I might not have been paying as much attention then. I guess I could continue to check in with each of the packges --- so far I've noticed this issue for [Evince](https://github.com/aronovgj/chocolatey/issues/2), [Neovim](https://github.com/rmolin88/choco-neovim/issues/1), and [Telegram](https://github.com/dtgm/chocolatey-packages/issues/303). 

Some contrasting examples: mpv, Nestopia, Rufus, and ZSNES don't install under the usual Program Files directory either; instead they install under `C:\ProgramData\chocolatey\lib` , which obviously isn't standard on Windows, but appears to be an alternate standard for Chocolatey. And adding Chocolatey's `bin` directory to the Path environment variable assures all applications installed there are accessible, without having to search throughout `C:\` or add a new entry to the Path every time you install something...

> You can also set custom install locations without needing the ubiquitous install directory switch, as mentioned in the documentation.

Eh?? How? Where does it say that? `--install-directory` is the only option I could find when I looked... :(

**Comment by ferventcoder** [comment]
> Some contrasting examples: mpv, Nestopia, Rufus, and ZSNES don't install under the usual Program Files directory either; instead they install under `C:\ProgramData\chocolatey\lib` , which obviously isn't standard on Windows, but appears to be an alternate standard for Chocolatey.

This is where you typically see portable types of packages or more true packaging - these are things that don't have the installers, they either have or obtain (and many times unpack) the runtime binaries. https://chocolatey.org/faq#what-distinction-does-chocolatey-make-between-an-installable-and-a-portable-application

**Comment by ferventcoder** [comment]
> Eh?? How? Where does it say that? `--install-directory` is the only option I could find when I looked... :(

https://chocolatey.org/faq#can-i-override-the-installation-directory (which points you to https://chocolatey.org/docs/getting-started#overriding-default-install-directory-or-other-advanced-install-concepts and https://chocolatey.org/docs/features-install-directory-override).

I did just add the following to the second link:

While you [can change the installation directory without this switch with even the open source Chocolatey edition](GettingStarted#overriding-default-install-directory), you will see that the ubiquitous switch makes it very easy and a low amount of work on your part.

You can see that now at https://github.com/chocolatey/choco/wiki/FeaturesInstallDirectoryOverride

**Comment by ferventcoder** [comment]
Fixed the link - it needs to be different as compared to the article was.

**Comment by Link-Satonaka** [comment]
>The community repository tries to keep the packaging aspect as vanilla as possible - there are numerous examples of when we've tried to add more sensible constructs and folks have balked at it. The few cases where an install path is chosen is like the Ruby package, as the locations it installs to are what is considered the best practices when you install multiple versions of Ruby.
I know that @Link-Satonaka has been looking to find more sensible defaults for all applications and (similar to what you are seeing), have guidelines to keep these apps out of user space. This is still in discussion, but I'm for it for the most part.

Hello! As mentioned, my approach involves moderating the repo such that AppData is never the *default* destination, but (as mentioned) that does indeed conflict with the other goal of keeping as vanilla as possible.

For the sake of discussion, I'll share my writeup of what might hypothetically be entered into the package creation documentation.
Comments, criticisms, and suggestions are welcome :) https://gist.github.com/Link-Satonaka/e29baa2da4ee2ff8e1bf19fb21614b76

**Comment by dufferzafar** [comment]
So, what is the suggested way to install Telegram via Chocolatey so that it works for all users?

Currently, I have two administrator accounts on my Windows machine and i installed `choco install telegram` via one account.

As expected, telegram was only available in that account and not in the other.

So in the other account I tried `choco install telegram --force` . But telegram was still not available in the second account.

**Comment by pauby** [comment]
@dufferzafar Telegram installing into AppData is a question for the software rather than Chocolatey. If the software allows it to be installed elsewhere then that is something that could be added via package parameters for example (or if the software supported it pass arguments directly to the installer).

Chocolatey manages the packages and the packages manage the software. But the package can only manage what the software allows.

**Comment by audreytoskin** [comment]
> So, what is the suggested way to install Telegram via Chocolatey so that it works for all users?

I've accepted that sometimes it's easier to install things manually, and then let each of those applications run its built-in automated update checks instead. The different `*setup.exe` installers you find out in the wild rarely document their command line options (or maybe don't develop them?), so it's hard to "fix" anything with the available CLI options.

With Telegram, for example, the installer wizard lets you choose the installation location, so installing manually and picking `C:\Program Files\` or whatever at least solves the issue of wanting a single installation for all users on a system. And then it will prompt for administrator confirmation and/or password when an update is available.

Updating everything at once with Chocolatey would have been better, but for the ones we can't, at least the applications being able to update themselves is pretty common. And the occasional app that doesn't update itself either, I've taken to running a PowerShell script which runs `choco upgrade` for me, but then also looks for updates specifically for these remaining applications too.

I realize now what I'd been asking for, in my original post, was basically to give us the Pro+ Ubiquitous Install feature for free, which y'know, seems like probably isn't going to happen. If you really need to do it with `choco` without subscribing, then you'd have to either convince the app packager that there's a good reason to override the application's default, or else ask the app developers to _change_ their default.
