### ISSUE TITLE
Store install options for upgrading

### ISSUE THREAD

**Issue by manhnt9** [chocolatey/choco#1812]
I set some install options when installing a package, CMake for example, enabling environment variables to be updated. But after upgrading I don't have CMake in PATH anymore.
So I think choco should remember install options and add them again in upgrade.
Reference: https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/987#issuecomment-488246471

**Comment by AdmiringWorm** [comment]
This is something that is already available in chocolatey, however you need to enable the `useRememberedArgumentsForUpgrades` feature for it to work.

Do note though, there are currently known problems with this feature. (I believe these are fixed in the latest beta, but I could be wrong)

**Comment by manhnt9** [comment]
OK, I'll watch for that feature, thanks!

**Comment by ferventcoder** [comment]
Duplicate of #797

**Comment by manhnt9** [comment]
This issue still presents. After upgrading CMake I loose it from PATH and cannot call cmake like before.

**Comment by manhnt9** [comment]
Sorry for bothering, long time no use Windows so I haven't enabled useRememberedArgumentsForUpgrades yet.
